// default package
// Generated 2016-11-21 9:37:57 by Hibernate Tools 3.5.0.Final
package com.cauc.contract.pojos;
import java.util.Date;

/**
 * Payment generated by hbm2java
 */
public class Payment implements java.io.Serializable {

	private int PId;
	private String PName;
	private Integer PFundBudgetType;
	private Integer PProcessState;
	private float PBuildFeeStandardPrice;
	private float PTrainFeeStandardPrice;
	private float PPaymentPercent;
	private String PContractId;
	private Integer PContractKey;
	private Integer PContractGrade;
	private Integer PGradeStudentCount;
	private float PReceiveMoney;
	private Date PReceiveDate;
	private float PTotalPrice;
	private Date PAddTime;
	private String PAddUser;
	private Date PLastModifyTime;
	private String PLastModifyUser;
	private int CCompy;
	private String PRemark;
	private float PMoney;
	private String PRealityDate;
	private Integer PStatus;
	private String PStage;
	private String PPrivateName;
	private Integer PCompy;
	private String PPicture;
	private String PNotice;
	private String PNoticeUrl;
	private Integer PNoticeStatus;
	private Integer PCurrentStage;
	private Integer PGeneralPhase;
	private String PStudentInfo;
	private String PAymentNumber;

	public Payment() {
	}

	public Payment(int PId, int CCompy) {
		this.PId = PId;
		this.CCompy = CCompy;
	}

	public Payment(int PId, String PName, Integer PFundBudgetType, Integer PProcessState, float PBuildFeeStandardPrice,
			float PTrainFeeStandardPrice, float PPaymentPercent, String PContractId, Integer PContractKey,
			Integer PContractGrade, Integer PGradeStudentCount, float PReceiveMoney, Date PReceiveDate,
			float PTotalPrice, Date PAddTime, String PAddUser, Date PLastModifyTime, String PLastModifyUser,
			int CCompy, String PRemark, float PMoney, String PRealityDate, Integer PStatus, String PStage,
			String PPrivateName, Integer PCompy, String PPicture, String PNotice, String PNoticeUrl,
			Integer PNoticeStatus, Integer PCurrentStage, Integer PGeneralPhase, String PStudentInfo,
			String PAymentNumber) {
		this.PId = PId;
		this.PName = PName;
		this.PFundBudgetType = PFundBudgetType;
		this.PProcessState = PProcessState;
		this.PBuildFeeStandardPrice = PBuildFeeStandardPrice;
		this.PTrainFeeStandardPrice = PTrainFeeStandardPrice;
		this.PPaymentPercent = PPaymentPercent;
		this.PContractId = PContractId;
		this.PContractKey = PContractKey;
		this.PContractGrade = PContractGrade;
		this.PGradeStudentCount = PGradeStudentCount;
		this.PReceiveMoney = PReceiveMoney;
		this.PReceiveDate = PReceiveDate;
		this.PTotalPrice = PTotalPrice;
		this.PAddTime = PAddTime;
		this.PAddUser = PAddUser;
		this.PLastModifyTime = PLastModifyTime;
		this.PLastModifyUser = PLastModifyUser;
		this.CCompy = CCompy;
		this.PRemark = PRemark;
		this.PMoney = PMoney;
		this.PRealityDate = PRealityDate;
		this.PStatus = PStatus;
		this.PStage = PStage;
		this.PPrivateName = PPrivateName;
		this.PCompy = PCompy;
		this.PPicture = PPicture;
		this.PNotice = PNotice;
		this.PNoticeUrl = PNoticeUrl;
		this.PNoticeStatus = PNoticeStatus;
		this.PCurrentStage = PCurrentStage;
		this.PGeneralPhase = PGeneralPhase;
		this.PStudentInfo = PStudentInfo;
		this.PAymentNumber = PAymentNumber;
	}

	public int getPId() {
		return this.PId;
	}

	public void setPId(int PId) {
		this.PId = PId;
	}

	public String getPName() {
		return this.PName;
	}

	public void setPName(String PName) {
		this.PName = PName;
	}

	public Integer getPFundBudgetType() {
		return this.PFundBudgetType;
	}

	public void setPFundBudgetType(Integer PFundBudgetType) {
		this.PFundBudgetType = PFundBudgetType;
	}

	public Integer getPProcessState() {
		return this.PProcessState;
	}

	public void setPProcessState(Integer PProcessState) {
		this.PProcessState = PProcessState;
	}

	public float getPBuildFeeStandardPrice() {
		return this.PBuildFeeStandardPrice;
	}

	public void setPBuildFeeStandardPrice(float PBuildFeeStandardPrice) {
		this.PBuildFeeStandardPrice = PBuildFeeStandardPrice;
	}

	public float getPTrainFeeStandardPrice() {
		return this.PTrainFeeStandardPrice;
	}

	public void setPTrainFeeStandardPrice(float PTrainFeeStandardPrice) {
		this.PTrainFeeStandardPrice = PTrainFeeStandardPrice;
	}

	public float getPPaymentPercent() {
		return this.PPaymentPercent;
	}

	public void setPPaymentPercent(float PPaymentPercent) {
		this.PPaymentPercent = PPaymentPercent;
	}

	public String getPContractId() {
		return this.PContractId;
	}

	public void setPContractId(String PContractId) {
		this.PContractId = PContractId;
	}

	public Integer getPContractKey() {
		return this.PContractKey;
	}

	public void setPContractKey(Integer PContractKey) {
		this.PContractKey = PContractKey;
	}

	public Integer getPContractGrade() {
		return this.PContractGrade;
	}

	public void setPContractGrade(Integer PContractGrade) {
		this.PContractGrade = PContractGrade;
	}

	public Integer getPGradeStudentCount() {
		return this.PGradeStudentCount;
	}

	public void setPGradeStudentCount(Integer PGradeStudentCount) {
		this.PGradeStudentCount = PGradeStudentCount;
	}

	public float getPReceiveMoney() {
		return this.PReceiveMoney;
	}

	public void setPReceiveMoney(float PReceiveMoney) {
		this.PReceiveMoney = PReceiveMoney;
	}

	public Date getPReceiveDate() {
		return this.PReceiveDate;
	}

	public void setPReceiveDate(Date PReceiveDate) {
		this.PReceiveDate = PReceiveDate;
	}

	public float getPTotalPrice() {
		return this.PTotalPrice;
	}

	public void setPTotalPrice(float PTotalPrice) {
		this.PTotalPrice = PTotalPrice;
	}

	public Date getPAddTime() {
		return this.PAddTime;
	}

	public void setPAddTime(Date PAddTime) {
		this.PAddTime = PAddTime;
	}

	public String getPAddUser() {
		return this.PAddUser;
	}

	public void setPAddUser(String PAddUser) {
		this.PAddUser = PAddUser;
	}

	public Date getPLastModifyTime() {
		return this.PLastModifyTime;
	}

	public void setPLastModifyTime(Date PLastModifyTime) {
		this.PLastModifyTime = PLastModifyTime;
	}

	public String getPLastModifyUser() {
		return this.PLastModifyUser;
	}

	public void setPLastModifyUser(String PLastModifyUser) {
		this.PLastModifyUser = PLastModifyUser;
	}

	public int getCCompy() {
		return this.CCompy;
	}

	public void setCCompy(int CCompy) {
		this.CCompy = CCompy;
	}

	public String getPRemark() {
		return this.PRemark;
	}

	public void setPRemark(String PRemark) {
		this.PRemark = PRemark;
	}

	public float getPMoney() {
		return this.PMoney;
	}

	public void setPMoney(float PMoney) {
		this.PMoney = PMoney;
	}

	public String getPRealityDate() {
		return this.PRealityDate;
	}

	public void setPRealityDate(String PRealityDate) {
		this.PRealityDate = PRealityDate;
	}

	public Integer getPStatus() {
		return this.PStatus;
	}

	public void setPStatus(Integer PStatus) {
		this.PStatus = PStatus;
	}

	public String getPStage() {
		return this.PStage;
	}

	public void setPStage(String PStage) {
		this.PStage = PStage;
	}

	public String getPPrivateName() {
		return this.PPrivateName;
	}

	public void setPPrivateName(String PPrivateName) {
		this.PPrivateName = PPrivateName;
	}

	public Integer getPCompy() {
		return this.PCompy;
	}

	public void setPCompy(Integer PCompy) {
		this.PCompy = PCompy;
	}

	public String getPPicture() {
		return this.PPicture;
	}

	public void setPPicture(String PPicture) {
		this.PPicture = PPicture;
	}

	public String getPNotice() {
		return this.PNotice;
	}

	public void setPNotice(String PNotice) {
		this.PNotice = PNotice;
	}

	public String getPNoticeUrl() {
		return this.PNoticeUrl;
	}

	public void setPNoticeUrl(String PNoticeUrl) {
		this.PNoticeUrl = PNoticeUrl;
	}

	public Integer getPNoticeStatus() {
		return this.PNoticeStatus;
	}

	public void setPNoticeStatus(Integer PNoticeStatus) {
		this.PNoticeStatus = PNoticeStatus;
	}

	public Integer getPCurrentStage() {
		return this.PCurrentStage;
	}

	public void setPCurrentStage(Integer PCurrentStage) {
		this.PCurrentStage = PCurrentStage;
	}

	public Integer getPGeneralPhase() {
		return this.PGeneralPhase;
	}

	public void setPGeneralPhase(Integer PGeneralPhase) {
		this.PGeneralPhase = PGeneralPhase;
	}

	public String getPStudentInfo() {
		return this.PStudentInfo;
	}

	public void setPStudentInfo(String PStudentInfo) {
		this.PStudentInfo = PStudentInfo;
	}

	public String getPAymentNumber() {
		return this.PAymentNumber;
	}

	public void setPAymentNumber(String PAymentNumber) {
		this.PAymentNumber = PAymentNumber;
	}

}
