// default package
// Generated 2016-8-11 9:59:16 by Hibernate Tools 3.6.0.Final
package com.cauc.contract.pojos;
import java.util.Date;

/**
 * LoginUser generated by hbm2java
 */
public class LoginUser implements java.io.Serializable {

	private int VId;
	private String VUsername;
	private String VPassword;
	private Date VCreateDate;
	private Integer VCreateUserId;
	private Integer VRoleId;
	private Date VLastModifyTime;
	private Integer VLastModiyUser;
	private Integer VLoginType;
	private Integer VAdminStatus;
	private String VRealname;

	public LoginUser() {
	}

	public LoginUser(int VId, String VUsername, String VPassword) {
		this.VId = VId;
		this.VUsername = VUsername;
		this.VPassword = VPassword;
	}

	public LoginUser(int VId, String VUsername, String VPassword, Date VCreateDate, Integer VCreateUserId,
			Integer VRoleId, Date VLastModifyTime, Integer VLastModiyUser, Integer VLoginType, Integer VAdminStatus,
			String VRealname) {
		this.VId = VId;
		this.VUsername = VUsername;
		this.VPassword = VPassword;
		this.VCreateDate = VCreateDate;
		this.VCreateUserId = VCreateUserId;
		this.VRoleId = VRoleId;
		this.VLastModifyTime = VLastModifyTime;
		this.VLastModiyUser = VLastModiyUser;
		this.VLoginType = VLoginType;
		this.VAdminStatus = VAdminStatus;
		this.VRealname = VRealname;
	}

	public int getVId() {
		return this.VId;
	}

	public void setVId(int VId) {
		this.VId = VId;
	}

	public String getVUsername() {
		return this.VUsername;
	}

	public void setVUsername(String VUsername) {
		this.VUsername = VUsername;
	}

	public String getVPassword() {
		return this.VPassword;
	}

	public void setVPassword(String VPassword) {
		this.VPassword = VPassword;
	}

	public Date getVCreateDate() {
		return this.VCreateDate;
	}

	public void setVCreateDate(Date VCreateDate) {
		this.VCreateDate = VCreateDate;
	}

	public Integer getVCreateUserId() {
		return this.VCreateUserId;
	}

	public void setVCreateUserId(Integer VCreateUserId) {
		this.VCreateUserId = VCreateUserId;
	}

	public Integer getVRoleId() {
		return this.VRoleId;
	}

	public void setVRoleId(Integer VRoleId) {
		this.VRoleId = VRoleId;
	}

	public Date getVLastModifyTime() {
		return this.VLastModifyTime;
	}

	public void setVLastModifyTime(Date VLastModifyTime) {
		this.VLastModifyTime = VLastModifyTime;
	}

	public Integer getVLastModiyUser() {
		return this.VLastModiyUser;
	}

	public void setVLastModiyUser(Integer VLastModiyUser) {
		this.VLastModiyUser = VLastModiyUser;
	}

	public Integer getVLoginType() {
		return this.VLoginType;
	}

	public void setVLoginType(Integer VLoginType) {
		this.VLoginType = VLoginType;
	}

	public Integer getVAdminStatus() {
		return this.VAdminStatus;
	}

	public void setVAdminStatus(Integer VAdminStatus) {
		this.VAdminStatus = VAdminStatus;
	}

	public String getVRealname() {
		return this.VRealname;
	}

	public void setVRealname(String VRealname) {
		this.VRealname = VRealname;
	}

}
