// default package
// Generated 2016-7-22 10:22:56 by Hibernate Tools 3.4.0.CR1
package com.cauc.contract.pojos;
import java.io.Serializable;
import java.util.Date;

/**
 * Dictionary generated by hbm2java
 */
public class Dictionary implements java.io.Serializable {

	private int dictionaryId;
	private String dictionaryName;
	private Integer level;
	private Integer parentId;
	private String childId;
	private Integer topId;
	private Date addTime;
	private Integer addUser;
	private Date lastModifyTime;
	private Integer lastModifyUser;

	public Dictionary() {
	}

	public Dictionary(int dictionaryId) {
		this.dictionaryId = dictionaryId;
	}

	public Dictionary(int dictionaryId, String dictionaryName, Integer level, Integer parentId, String childId,
			Integer topId, Date addTime, Integer addUser, Date lastModifyTime, Integer lastModifyUser) {
		this.dictionaryId = dictionaryId;
		this.dictionaryName = dictionaryName;
		this.level = level;
		this.parentId = parentId;
		this.childId = childId;
		this.topId = topId;
		this.addTime = addTime;
		this.addUser = addUser;
		this.lastModifyTime = lastModifyTime;
		this.lastModifyUser = lastModifyUser;
	}

	public int getDictionaryId() {
		return this.dictionaryId;
	}

	public void setDictionaryId(int dictionaryId) {
		this.dictionaryId = dictionaryId;
	}

	public String getDictionaryName() {
		return this.dictionaryName;
	}

	public void setDictionaryName(String dictionaryName) {
		this.dictionaryName = dictionaryName;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getChildId() {
		return this.childId;
	}

	public void setChildId(String childId) {
		this.childId = childId;
	}

	public Integer getTopId() {
		return this.topId;
	}

	public void setTopId(Integer topId) {
		this.topId = topId;
	}

	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	public Integer getAddUser() {
		return this.addUser;
	}

	public void setAddUser(Integer addUser) {
		this.addUser = addUser;
	}

	public Date getLastModifyTime() {
		return this.lastModifyTime;
	}

	public void setLastModifyTime(Date lastModifyTime) {
		this.lastModifyTime = lastModifyTime;
	}

	public Integer getLastModifyUser() {
		return this.lastModifyUser;
	}

	public void setLastModifyUser(Integer lastModifyUser) {
		this.lastModifyUser = lastModifyUser;
	}

}
